#!/bin/bash
PWD="$(pwd)"
SCRIPT=$(readlink -f "$0")
BASEDIR="$( cd "$(dirname "$SCRIPT")" ; pwd -P )"

#make sure we got url(s) to use
if [ -z "$1" ]; then
    echo "Usage: mageimport [sql_file] [ [unsecure_url] [secure_url] ]"
    echo "       Drops, re-creates, and imports the Magento DB using Magerun."
else
  #check Magento version
  if [ -f "$PWD/app/etc/local.xml" ]; then
    #Magento 1
    echo "Detected Magento Version 1.x"
    MAGERUN="$BASEDIR/magerun"
    MAGEVERSION=1
  elif [ -f "$PWD/app/etc/env.php" ]; then
    #Magento 2
    echo "Detected Magento Version 2.x"
    MAGERUN="$BASEDIR/magerun2"
    MAGEVERSION=2
  else
    echo "Could not detect Magento Version"
    echo "Ensure that you run the mageimport command from the Magento site root."
  fi

  #change the site url
  if [[ $MAGEVERSION == 1 || $MAGEVERSION == 2 ]]; then
    "$MAGERUN" db:drop -f
    "$MAGERUN" db:create
    #import using gzip if needed
    if [[ $1 == *".gz"* ]]; then
      "$MAGERUN" db:import -c gzip "$1"
    else
      "$MAGERUN" db:import "$1"
    fi
    #rebuild the environment
    echo "Rebuilding the environment using mageafterpull"
    "$BASEDIR/mageafterpull"
    #set the URLs if provided using the magelocalize helper
    if [[ -n $2 && -n $3 ]]; then
      echo "Localizing imported DB using magelocalize"
      "$BASEDIR/magelocalize" "$2" "$3"
    fi
    #reindex everything
    echo "Reindexing via magerun"
    "$MAGERUN" indexer:reindex
  fi

  echo "Done!"
fi