#!/bin/bash
if [ -z "$1" ]; then
    echo "Usage: php-version <7.3|7.2|7.1|7.0|5.6>"
    echo "       Changes the current PHP version used by the system and valet-linux at the same time."
    php --version
else
    #stop all current versions of PHP
    sudo service php5.6-fpm stop
    sudo service php7.0-fpm stop
    sudo service php7.1-fpm stop
    sudo service php7.2-fpm stop
    sudo service php7.3-fpm stop
    #disable all current versions of PHP
    sudo systemctl disable php5.6-fpm php7.0-fpm php7.1-fpm php7.2-fpm php7.3-fpm
    #start the correct version of PHP and make it the active CLI version
    sudo service "php$1-fpm" start
    sudo update-alternatives --set php "/usr/bin/php$1"
    sudo systemctl enable "php$1-fpm"
    #force a composer global update to re-install php-version appropriate dependencies
    composer global update
    #tell valet to use this version of php
    valet use "$1"
    #restart valet services
    valet restart
fi