#!/bin/bash
SCRIPT=$(readlink -f "$0")
BASEDIR="$( cd "$(dirname "$SCRIPT")" ; pwd -P )"
if [ -z "$1" ]; then
    echo "Usage: vpn-connect [portal.example.com]"
    echo "       Connects to a GlobalProtect VPN Portal using web-based authentication."
    echo "       If a portal is not specified, we will automatically attempt to connect to the last portal used."
    if [ -r "$BASEDIR/.last-vpn-portal" ]; then
      PORTAL="$(cat "$BASEDIR/.last-vpn-portal")"
      echo ""
      echo ""
      echo "No portal specified, connect to last used portal $PORTAL?"
      read -rp "Hit [enter] to continue connecting to the last portal or ctrl-c to abort"
      sudo echo "Connecting to $PORTAL"
    fi
else
    sudo echo "Connecting to $1"
    echo "$1" > "$BASEDIR/.last-vpn-portal"
    PORTAL="$1"
fi

eval $( "$BASEDIR/gp-saml-gui.py" -v "$PORTAL" )
echo "$COOKIE" | sudo openconnect --protocol=gp -u "$USER" --passwd-on-stdin "$HOST" --interface="gpvpn" --script="$BASEDIR/vpnc-script" --csd-wrapper="/usr/lib/x86_64-linux-gnu/openconnect/hipreport.sh"